-- geographic_analysis.sql
-- This script analyses user distribution by geography and identifies top-performing brands.
-- It also compares regional revenue based on predefined city groupings.

-- SECTION 1: User Distribution and Top-Performing Brands
-- Identifies the top-performing brands based on purchase frequency.
SELECT
  pa.item_brand, -- The seller or brand
  pa.item_name, -- The specific item name
  COUNT(ti.transaction_id) AS purchase_frequency -- Frequency of purchases for each item
FROM
  prism-insights.prism_acquire.transactionsanditems ti
JOIN
  prism-insights.prism_acquire.productattributes pa ON ti.item_id = pa.item_id
JOIN
  prism-insights.prism_acquire.product_listprices pi ON ti.item_id = pi.item_id
JOIN
  prism-insights.prism_acquire.transactions t ON ti.transaction_id = t.transaction_id
GROUP BY
  pa.item_brand, pa.item_name
HAVING
  COUNT(ti.transaction_id) > 50 -- Threshold for top-selling products
ORDER BY
  purchase_frequency DESC
LIMIT 10;

-- SECTION 2: Regional Revenue Comparisons
-- Groups cities into predefined regions and calculates total revenue per region.
SELECT
    CASE
        WHEN city IN ('London', 'Bristol', 'Southampton') THEN 'South'
        WHEN city IN ('Birmingham', 'Coventry') THEN 'Midlands'
        WHEN city IN ('Manchester', 'Leeds', 'Liverpool') THEN 'North'
        WHEN city IN ('Norwich', 'Cambridge') THEN 'East'
        ELSE 'Other' -- Any cities not specified are grouped as "Other"
    END AS region,
    SUM(total_revenue) AS total_revenue -- Total revenue generated by each region
FROM
    prism-insights.prism_acquire.users
GROUP BY 1
ORDER BY total_revenue DESC; -- Orders regions by revenue contribution
